# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tagging_pb2 as tagging__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tagging_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MediaTaggingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tag = channel.unary_unary(
                '/media_tagging.MediaTaggingService/Tag',
                request_serializer=tagging__pb2.TagRequest.SerializeToString,
                response_deserializer=tagging__pb2.TagResponse.FromString,
                _registered_method=True)
        self.Describe = channel.unary_unary(
                '/media_tagging.MediaTaggingService/Describe',
                request_serializer=tagging__pb2.DescribeRequest.SerializeToString,
                response_deserializer=tagging__pb2.DescribeResponse.FromString,
                _registered_method=True)


class MediaTaggingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Tag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Describe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaTaggingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tag': grpc.unary_unary_rpc_method_handler(
                    servicer.Tag,
                    request_deserializer=tagging__pb2.TagRequest.FromString,
                    response_serializer=tagging__pb2.TagResponse.SerializeToString,
            ),
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=tagging__pb2.DescribeRequest.FromString,
                    response_serializer=tagging__pb2.DescribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'media_tagging.MediaTaggingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('media_tagging.MediaTaggingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaTaggingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Tag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_tagging.MediaTaggingService/Tag',
            tagging__pb2.TagRequest.SerializeToString,
            tagging__pb2.TagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media_tagging.MediaTaggingService/Describe',
            tagging__pb2.DescribeRequest.SerializeToString,
            tagging__pb2.DescribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
