apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "media-similarity.fullname" . }}
  labels:
    {{- include "media-similarity.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "media-similarity.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "media-similarity.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "media-similarity.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: deps-volume
          emptyDir: {}
      initContainers:
        {{- if or  .Values.mediaSimilarity.taggingDb.enabled .Values.mediaSimilarity.similarityDb.enabled }}
        - name: install-postres-driver
          image: ghcr.io/astral-sh/uv:0.10-python3.13-trixie
          command: ["uv", "pip", "install"]
          args:
            - "--target"
            - "/shared-deps"
            - "psycopg2-binary"
          volumeMounts:
            - name: deps-volume
              mountPath: /shared-deps
        {{- end }}
        {{- with .Values.initContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if or  .Values.mediaSimilarity.taggingDb.enabled .Values.mediaSimilarity.similarityDb.enabled }}
              - name: deps-volume
                mountPath: /shared-deps
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            {{- if .Values.mediaSimilarity.taggingDb.enabled }}
            - name: MEDIA_TAGGING_DB_URL
              value: {{ include "media-similarity.mediaTaggingDb" . | quote }}
            {{- end }}
            {{- if .Values.mediaSimilarity.similarityDb.enabled }}
            - name: SIMILARITY_DB_URL
              value: {{ include "media-similarity.mediaSimilarityDb" . | quote }}
            {{- end }}
            {{- with .Values.env }}
            {{- include "media-similarity.renderEnv" . | nindent 12 }}
            {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
