apiVersion: v2
name: media-similarity
description: A Helm chart for Filonov's media similarity
type: application
version: 0.1.0
appVersion: "0.10.0"
dependencies:
   - name: postgresql
     condition: mediaSimilarity.taggingDb.enabled, mediaSimilarity.similarityDb.enabled
     version: "15.x.x"
     repository: https://charts.bitnami.com/bitnami
