# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import filonov_pb2 as filonov__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in filonov_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FilonovServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateCreativeMap = channel.unary_unary(
                '/filonov.FilonovService/GenerateCreativeMap',
                request_serializer=filonov__pb2.GenerateCreativeMapRequest.SerializeToString,
                response_deserializer=filonov__pb2.Operation.FromString,
                _registered_method=True)
        self.GenerateTables = channel.unary_unary(
                '/filonov.FilonovService/GenerateTables',
                request_serializer=filonov__pb2.GenerateTablesRequest.SerializeToString,
                response_deserializer=filonov__pb2.Operation.FromString,
                _registered_method=True)
        self.GetOperation = channel.unary_unary(
                '/filonov.FilonovService/GetOperation',
                request_serializer=filonov__pb2.GetOperationRequest.SerializeToString,
                response_deserializer=filonov__pb2.Operation.FromString,
                _registered_method=True)
        self.ListOperations = channel.unary_unary(
                '/filonov.FilonovService/ListOperations',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=filonov__pb2.ListOperationsResponse.FromString,
                _registered_method=True)


class FilonovServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateCreativeMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilonovServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateCreativeMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCreativeMap,
                    request_deserializer=filonov__pb2.GenerateCreativeMapRequest.FromString,
                    response_serializer=filonov__pb2.Operation.SerializeToString,
            ),
            'GenerateTables': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTables,
                    request_deserializer=filonov__pb2.GenerateTablesRequest.FromString,
                    response_serializer=filonov__pb2.Operation.SerializeToString,
            ),
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=filonov__pb2.GetOperationRequest.FromString,
                    response_serializer=filonov__pb2.Operation.SerializeToString,
            ),
            'ListOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOperations,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=filonov__pb2.ListOperationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'filonov.FilonovService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('filonov.FilonovService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FilonovService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateCreativeMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filonov.FilonovService/GenerateCreativeMap',
            filonov__pb2.GenerateCreativeMapRequest.SerializeToString,
            filonov__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filonov.FilonovService/GenerateTables',
            filonov__pb2.GenerateTablesRequest.SerializeToString,
            filonov__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filonov.FilonovService/GetOperation',
            filonov__pb2.GetOperationRequest.SerializeToString,
            filonov__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/filonov.FilonovService/ListOperations',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            filonov__pb2.ListOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
