name: Run tests media-tagging

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'libs/media_tagging/**'
env:
  UV_SYSTEM_PYTHON: 1

permissions: {}
jobs:
  test-unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup uv
        uses: astral-sh/setup-uv@e4db8464a088ece1b920f60402e813ea4de65b8f
        with:
          version: "0.5.4"
          enable-cache: true
      - name: Install dependencies
        run: |
          uv pip install pytest pytest-mock
          uv pip install -e libs/media_tagging/[all]
      - name: Test media-tagging
        run: |
          cd libs/media_tagging
          pytest -m 'not cloud' tests/unit
        env:
          GEMINI_API_KEY: test-key
