name: Run tests filonov

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'libs/filonov/**'
env:
  UV_SYSTEM_PYTHON: 1

jobs:
  test-unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.4"
          enable-cache: true
      - name: Install dependencies
        run: |
          uv pip install pytest coverage
      - name: Test filonov
        run: |
          uv pip install -e libs/media_tagging/.[all]
          uv pip install -e libs/media-fetching/
          uv pip install -e libs/media_similarity/
          uv pip install -e libs/filonov/[all]
          cd libs/filonov
          pytest tests/unit
